export const REGISTER_REQUEST= 'USERS_REGISTER_REQUEST';
export const REGISTER_SUCCESS= 'USERS_REGISTER_SUCCESS';
export const REGISTER_FAILURE= 'USERS_REGISTER_FAILURE';

export const LOGIN_REQUEST= 'USERS_LOGIN_REQUEST';
export const LOGIN_SUCCESS= 'USERS_LOGIN_SUCCESS';
export const LOGIN= 'LOGIN';
export const LOGOUT= 'LOGOUT';
export const AUTHENTICATED = 'AUTHENTICATED';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const AUTH_ERROR = 'AUTH_ERROR'
export const SET_TERM = 'SET_TERM';
export const INVALID_TERM = 'INVALID_TERM';
export const REQUEST_MEDICATIONS = 'REQUEST_MEDICATIONS';
export const RECEIVE_MEDICATIONS = 'RECEIVE_MEDICATIONS';
export const POST_USER_MEDICATIONS = 'POST_USER_MEDICATIONS';
export const GET_USER_MEDICATIONS = 'GET_USER_MEDICATIONS';
export const GET_USER_INTERACTIONS = 'GET_USER_INTERACTIONS';
